version: "3.5"

x-environment:
  &default-environment
  #### Uncomment and configure the following if you are behind a proxy
    - JAVA_HTTP_PROXY=-Dhttp.proxyHost=146.124.225.18 -Dhttp.proxyPort=3128
    - JAVA_HTTPS_PROXY=-Dhttps.proxyHost=146.124.225.18 -Dhttps.proxyPort=3128 
    - JAVA_SOCKS_PROXY=-DsocksProxyHost=146.124.225.18 -DsocksProxyPort=3128
    - JAVA_NON_PROXY_HOSTS=-Dhttp.nonProxyHosts=*symbiote-h2020.eu|*intracom-telecom.com|symbiote-coreconfig|symbiote-aam|symbiote-eureka|symbiote-mongo|localhost|10.*.*.*
   # _JAVA_OPTIONS=-Dhttps.proxyHost=146.124.225.18 -Dhttps.proxyPort=3128 -Dhttp.proxyHost=146.124.225.18 -Dhttp.proxyPort=3128 $JAVA_NON_PROXY_HOSTS -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Dhttp.sslVerify=false
    - _JAVA_OPTIONS= -Dhttps.proxyHost=146.124.225.18 -Dhttps.proxyPort=3128  $JAVA_NON_PROXY_HOSTS -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Dhttp.sslVerify=false
    - TZ=Europe/Athens   

#- _JAVA_OPTIONS=$JAVA_HTTP_PROXY
    - http_proxy=http://146.124.225.18:3128
    - https_proxy=http://146.124.225.18:3128
    - no_proxy=localhost,127.0.0.0,127.0.1.1,10.*.*.*
services:
  symbiote-rabbitmq:
    image: rabbitmq:3-alpine
    networks:
      - symbiote
    ports:
      - 5671:5671
      - 5672:5672
  symbiote-mongo:
    environment: *default-environment
    image: mongo:3.6
    networks:
      - symbiote
    ports:
      - 27017:27017
    volumes:
      - symbiote-core-vol:/data/db
  symbiote-coreconfig:
    environment: *default-environment
    image: symbioteh2020/symbiote-coreconfig:3.0.5
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - symbiote
    volumes:
      - symbiote-vol-config:/home/CoreConfigProperties
    ports:
      - 8888:8888
  symbiote-aam:
    environment: *default-environment
    image: symbioteh2020/symbiote-aam:5.0.12
    depends_on:
      - symbiote-rabbitmq
      - symbiote-mongo
      - symbiote-coreconfig
    deploy:
      resources:
        limits:
          memory: 1000M
    networks:
      - symbiote
    secrets:
      - source: aambootstrapconfig
        target: /home/bootstrap.properties
      - source: aamkeystore
        target: /home/core.p12
  symbiote-eureka:
    environment: *default-environment
    image: symbioteh2020/symbiote-eureka:3.0.2
    deploy:
      resources:
        limits:
          memory: 400M
    networks:
      - symbiote
    ports:
      - 8761:8761
    secrets:
      - source: eurekaconfig
        target: /home/bootstrap.properties
  symbiote-admin:
    environment: *default-environment
#    image: symbioteh2020/symbiote-admin:3.1.6
    image: administration-3.1.6:latest
    depends_on:
      - symbiote-aam
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - symbiote
    secrets:
      - source: adminconfig
        target: /home/bootstrap.properties
  symbiote-coreinterface:
    environment: *default-environment
    image: symbioteh2020/symbiote-coreinterface:3.0.3
    depends_on:
      - symbiote-aam
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - symbiote
    secrets:
      - source: ciconfig
        target: /home/bootstrap.properties
  symbiote-cloudcoreinterface:
    environment: *default-environment
    image: symbioteh2020/symbiote-cloudcoreinterface:3.0.3
    depends_on:
      - symbiote-aam
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - symbiote
    secrets:
      - source: cciconfig
        target: /home/bootstrap.properties
  symbiote-cram:
    environment: *default-environment
    image: symbioteh2020/symbiote-cram:3.0.6
    depends_on:
      - symbiote-aam
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - symbiote
    secrets:
      - source: cramconfig
        target: /home/bootstrap.properties
  symbiote-crm:
    environment: *default-environment
    image: symbioteh2020/symbiote-crm:3.0.2
    depends_on:
      - symbiote-aam
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - symbiote
    secrets:
      - source: crmconfig
        target: /home/bootstrap.properties
  symbiote-registry:
    environment: *default-environment
    image: symbioteh2020/symbiote-registry:3.0.4
    #image: registry_testing
    depends_on:
      - symbiote-aam
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - symbiote
    secrets:
      - source: registryconfig
        target: /home/bootstrap.properties
  symbiote-search:
    environment: *default-environment
    image: symbioteh2020/symbiote-search:3.0.13
    depends_on:
      - symbiote-aam
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - symbiote
    volumes:
      - symbiote-search-triplestore:/home/coreSearchTriplestore
    secrets:
      - source: searchconfig
        target: /home/bootstrap.properties
  symbiote-semanticmanager:
    environment: *default-environment
    image: symbioteh2020/symbiote-semanticmanager:3.0.3
    depends_on:
      - symbiote-aam
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - symbiote
    secrets:
      - source: smconfig
        target: /home/bootstrap.properties
  symbiote-bt:
    environment: *default-environment
    image: symbioteh2020/symbiote-bt:3.0.5
    command: sh -c 'java -DSPRING_BOOT_WAIT_FOR_SERVICES=symbiote-coreinterface:8100 -Xmx1024m -Duser.home=/home -Dspring.output.ansi.enabled=NEVER -jar $$(ls *run.jar)'
    depends_on:
      - symbiote-aam
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - symbiote
    secrets:
      - source: btconfig
        target: /home/bootstrap.properties

networks:
  symbiote:
    name: symbiote
volumes:
  symbiote-vol-config:
  symbiote-core-vol:
  symbiote-search-triplestore:
secrets:
  eurekaconfig:
    file: ./bootstrap.properties
  aambootstrapconfig:
    file: ./AuthenticationAuthorizationManager/bootstrap.properties
  aamkeystore:
    file: ./core.p12
  adminconfig:
    file: ./bootstrap.properties
  ciconfig:
    file: ./CoreInterface/bootstrap.properties
  cciconfig:
    file: ./bootstrap.properties
  cramconfig:
    file: ./bootstrap.properties
  crmconfig:
    file: ./bootstrap.properties
  registryconfig:
    file: ./bootstrap.properties
  searchconfig:
    file: ./bootstrap.properties
  smconfig:
    file: ./bootstrap.properties
  btconfig:
    file: ./bootstrap.properties
